filePaths: "pvx/sales-orders.json,pvx/sales-order-items.json,pvx/customers.json,wpl/sales-orders.json"

mule:
  p-inventory:
    client_id: "40405c2f1ba84b739867373c457f2dbb"
    client_secret: "00683736750C415994fbAe0Cf822D290"
    
  p-api-co-pvx-os-statusevents:
    client_id: "fa6037665f69464b8ce3323487b8318b"
    client_secret: "25D4963d95c0477C9128C3BabFB63DD4"
    
  p-inventory-whip:
    client_id: "355efad188f2449bad0584c0578ab210"
    client_secret: "e52F3d1a0FE74361B7aF118e82774240"
    
  p-forders-pub:
    client_id: "355efad188f2449bad0584c0578ab210"
    client_secret: "e52F3d1a0FE74361B7aF118e82774240"
    
blazemeter-mock-service:
  wait: "2" #secs
  host: "ckmulesoftredirectmockservice308531.mock.blazemeter.com"
  port: "443"

object-store:
  ttl: "10" #mins
  
http:
  timeout: "180000" #milisecs
