filePaths: "pvx/sales-orders.csv,pvx/sales-order-items.csv,pvx/customers.csv,wpl/sales-orders.csv"

mule:
  p-inventory:
    client_id: "daa0dedb9b9f496aa64b5014dafcd2ef"
    client_secret: "83ddb32B0ff7426CAb89Ff94aAd494BE"
    
  p-api-co-pvx-os-statusevents:
    client_id: "daa0dedb9b9f496aa64b5014dafcd2ef"
    client_secret: "83ddb32B0ff7426CAb89Ff94aAd494BE"
    
  p-inventory-whip:
    client_id: "daa0dedb9b9f496aa64b5014dafcd2ef"
    client_secret: "83ddb32B0ff7426CAb89Ff94aAd494BE"
    
  p-forders-pub:
    client_id: "daa0dedb9b9f496aa64b5014dafcd2ef"
    client_secret: "83ddb32B0ff7426CAb89Ff94aAd494BE"
    
blazemeter-mock-service:
  wait: "2" #secs
  host: "ckmulesoftredirectmockservice308531.mock.blazemeter.com"
  port: "443"

object-store:
  ttl: "10" #mins
  
http:
  timeout: "180000" #milisecs
  
file:
  timeBetweenSizeCheck: "2" #secs
  
json.logger:
## Priority/Levels of logging  
  priority:
    warn: WARN
    error: ERROR
    info: INFO
    debug: DEBUG
            
## Following are some sample Keyfields for better log filtering. Modify the keyfields
## depending your application needs.           
  keyFields:
    keyField01: "product_id"
    keyField02: "parent_id"
    keyField03: "customer_id"
    keyField04: "sku"

## tracePoint/Stages of the application at which you may want to log.    
  tracePoint:
    start: START
    beforeTransformation: BEFORE_TRANSFORMATION
    afterTransformation: AFTER_TRANSFORMATION
    beforeRequest: BEFORE_REQUEST
    afterRequest: AFTER_REQUEST
    enterFlow: ENTER_FLOW
    exitFlow: EXIT_FLOW
    end: END
    exception: EXCEPTION
    processing: PROCESSING