mule:
  p-inventory:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-api-co-pvx-os-statusevents:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-inventory-whip:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-forders-pub:
    client_id: "passIn"
    client_secret: "passIn"
    
outbound:
  host: "qa.ipaas.tfapparel.net"
  port: "443"
  maxConcurrency: "20"

  wpl:
    fulfillment:
      scheduler:
        frequency: "0 0/5 * 1/1 * ? *" # this will run every 5 minutes
      db:
        timeDiff: "300" #secs
        limit: "50"

    inventory:
      scheduler:
        frequency: "0 0/2 * 1/1 * ? *" # this will run every 2 minutes
      db:
        limit: "50"

    statusChange:
      scheduler:
        frequency: "0 0/2 * 1/1 * ? *" # this will run every 2 minutes
      db:
        limit: "50"

  pvx:
    inventory:
      scheduler:
        frequency: "0 0/2 * 1/1 * ? *" # this will run every 2 minutes
      db:
        limit: "50"

    statusChange:
      scheduler:
        frequency: "0 0/2 * 1/1 * ? *" # this will run every 2 minutes
      db:
        limit: "50"

peoplevox:
  inventory: "true"
  statusChange: "true"
  fulfillment: "false"

whiplash:
  inventory: "true"
  statusChange: "true"
  fulfillment: "false"

jdbc:
  hostName: "0.0.0.0"
  port: "3306"
  databaseName: "mulesoft-dev"
  user: "passIn"
  password: "passIn"