mule:
  p-inventory:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-api-co-pvx-os-statusevents:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-inventory-whip:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-forders-pub:
    client_id: "passIn"
    client_secret: "passIn"
    
outbound:
  waitBeforeCallingFulfillmentRequest: "300" #secs
  waitBeforeCallingInventoryRequest: "5" #secs
  waitBetweenInventoryRequests: "2" #secs
  host: "qa.ipaas.tfapparel.net"
  port: "443"
  maxConcurrency: "20"

peoplevox:
  inventory: "true"
  statusChange: "true"
  fulfillment: "true"

whiplash:
  inventoryATS: "true"
  statusChange: "true"
  fulfillment: "true"

jdbc:
  hostName: "0.0.0.0"
  port: "3306"
  databaseName: "mulesoft-dev"
  user: "passIn"
  password: "passIn"