mule:
  p-inventory:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-api-co-pvx-os-statusevents:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-inventory-whip:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-forders-pub:
    client_id: "passIn"
    client_secret: "passIn"
    
outbound:
  waitAfterFinishFlow: "60" #secs
  waitBetweenRequests: "2" #secs
  host: "qa.ipaas.tfapparel.net"
  port: "443"
  
jdbc:
  hostName: "mulesoft-integration-test.c7iscturzbsa.ap-southeast-2.rds.amazonaws.com"
  port: "3306"
  databaseName: "mulesoft-dev"
  user: "passIn"
  password: "passIn"