mule:
  p-inventory:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-api-co-pvx-os-statusevents:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-inventory-whip:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-forders-pub:
    client_id: "passIn"
    client_secret: "passIn"
    
outbound:
  host: "qa.ipaas.tfapparel.net"
  port: "443"
  maxConcurrency: "20"

  fulfillment:
    scheduler:
      frequency: "0 0/5 * 1/1 * ? *" # this will run every 5 minutes
    db:
      timeDiff: "300" #secs
      limit: "50"

peoplevox:
  inventory: "true"
  statusChange: "true"
  fulfillment: "true"

whiplash:
  inventory: "true"
  statusChange: "true"
  fulfillment: "true"
  
jdbc:
  hostName: "mulesoft-integration-test.c7iscturzbsa.ap-southeast-2.rds.amazonaws.com"
  port: "3306"
  databaseName: "mulesoft-dev"
  user: "passIn"
  password: "passIn"